### ISSUE TITLE
OTP generated by arduino using rtc and OTP generated by google authenticator does not match

### ISSUE THREAD

**Issue by Sunam-Rijal** [lucadentella/TOTP-Arduino#10]
I use same code that you posted and change the hmacKey by using my own secret key from the webpage provided by you and the QR-code was scanned by google authenticator and upload code to arduino but the OTP's are different. Please suggest the solution...

**Comment by lucadentella** [comment]
please check the timezone, Google authentication uses UTC so you must adopt the same

**Comment by Sunam-Rijal** [comment]
I need to replace GMT by UTC right????

**Comment by lucadentella** [comment]
You must set the time on Arduino (RTC or what source you're using) to the correct UTC time... be sure that your smartphone and your arduino are in sync

**Comment by Sunam-Rijal** [comment]
Can you please suggest how to synchronize the time of arduino and smartphone??

**Comment by lucadentella** [comment]
I expect your smartphone is automatically synced with time providers. 

You may use the same for Arduino:
- sync with an NTP server (https://www.arduino.cc/en/Tutorial/UdpNTPClient)
- sync via GPS (https://learn.adafruit.com/arduino-clock)
- sync from radio signals (http://arduino-projects4u.com/dcf77/)
...

**Comment by Sunam-Rijal** [comment]
ohhh, that means i need to add one more module either GPS/wifi right????

**Comment by lucadentella** [comment]
no, that means that you have several options to keep the time in Arduino... you can also use a simple RTC chip but it must be initialized precisely. this is a requirement for any time-based OTP. 
I'm closing this because it's not a issue related to the code of this library.

**Comment by Sunam-Rijal** [comment]
ok, thanks for answering my questions and give some idea which will be useful for my project. Thank you so much.
