### ISSUE TITLE
fatal error: avr/io.h: No such file or directory

### ISSUE THREAD

**Issue by bert2002** [lucadentella/TOTP-Arduino#11]
Hi,
trying to get this running, but it seems that some files are missing or not working in the latest Arduino versions, I am getting this
```
~/Arduino/libraries/Sha/sha1.cpp:2:20: fatal error: avr/io.h: No such file or directory
 Used: ~/.arduino15/packages/esp32/hardware/esp32/1.0.4/libraries/WiFi
compilation terminated.
```

Any idea where to get these?

Thanks,
bert

**Comment by bert2002** [comment]
I just found out that the code here is updated, just not the one in the Arduino code. The code here works kind of, even so I cant get it verified.

**Comment by lucadentella** [comment]
Updated the library version, in some hours it should be visible in Arduino IDE. 
Tested the new example with esp32 and works.
