### ISSUE TITLE
change hmacKey

### ISSUE THREAD

**Issue by diasrobson** [lucadentella/TOTP-Arduino#15]
Hi, there amazing work on this library works really well. this is more of a feater request than a bug.

I was wondering if you could make it so the hmacKey could be changed/updated in code, as I want to use the Chip ID as the hmacKey but from what I can see ill have to do that manually  at the moment 

thanks for all your works :)

**Comment by lucadentella** [comment]
Hi, I can't fully understand your question... you pass the key to the TOTP object:

`TOTP(uint8_t* hmacKey, int keyLength);`

so you can create a new object with an updated key... isn't it what you were looking for? 
thanks!

**Comment by diasrobson** [comment]
i was wondering if I could edit the key in the object incode using e.g the serial monitor
