### ISSUE TITLE
sha1.cpp includes unnecessary AVR headers

### ISSUE THREAD

**Issue by benjaminkraus** [lucadentella/TOTP-Arduino#2]
I attempted to use this project on an ESP8266, but I ran into an issue with the two AVR headers that are included in sha1.cpp:

```
#include <avr/io.h>
#include <avr/pgmspace.h>
```

These were incompatible with the ESP8266. However, as far as I can tell these two headers are unnecessary. I removed those two lines and everything seems to be working just fine.

I've got my project working for my own needs, but I plan on posting it to GitHub and other won't be able to use my code without similarly modifying sha1.cpp. For the sake of others who are trying to use this code, you may want to remove those two headers.

**Comment by hpsaturn** [comment]
Same situation on my project but I using ESP32 and my project is a `platformio` project.
