### ISSUE TITLE
Cant make it work

### ISSUE THREAD

**Issue by arifainchtein** [lucadentella/TOTP-Arduino#9]
Hello,
I have tried reproducing your example but the code generated never matches other freeotp generators.  I have tried FreeOTP on IOS and https://totp.danhersam.com/.  
Using the secret as per your example, MyLegoDoor, those the totp generators produced the same code, but the one running in the arduino does not.

I am using DFRobot Gravity 2405 RTC to get the time, and verified that is producing the right value for seconds since 1970.

Any chance you could look at the example i included?

Thanks
[testtotp.zip](https://github.com/lucadentella/TOTP-Arduino/files/2301474/testtotp.zip)

**Comment by bert2002** [comment]
Any luck?

**Comment by lucadentella** [comment]
I've just uploaded a full working example, please check
